const initValue = {
    details: [
        {
            'id': 1,
            'name': 'Stella Johnson',
            'email': 'stella.johnson@example.com',
            'phone': '+1-215-659-7529',
            'companyName': 'Tata Group',
            'gender': "male",
            'address': `7032 Glenwood Court New Rochelle, NY 10801`,
        }, {
            'id': 2,
            'name': 'Garry Sobars',
            'email': 'garry.sobars@example.com',
            'phone': '+1-215-745-7529',
            'companyName': 'Life Insurance Corporation of India',
            'gender': "male",
            'address': `443 Mill Pond Court Kingsport, TN 37660`,
        },
        {
            'id': 3,
            'name': 'Alex Dolgove',
            'email': 'alex.dolgove@example.com',
            'phone': '+1-215-748-7855',
            'companyName': 'Bharti Airtel Limited',
            'gender': "male",
            'address': '822 SE. Albany Road Vernon Rockville, CT 06066',
        }, {
            'id': 4,
            'name': 'Domnic Brown',
            'email': 'domnic.brown@example.com',
            'phone': '+1-215-756-4579',
            'companyName': 'Infosys Limited',
            'gender': "male",
            'address': '16 3rd Road Gallatin, TN 37066',
        }, {
            'id': 5,
            'name': 'Kadir M',
            'email': 'kadir.m@example.com',
            'phone': '+1-215-659-7586',
            'companyName': 'State Bank of India',
            'gender': 'male',
            'address': '440 Military Ave. Pelham, AL 35124',
        }, {
            'id': 6,
            'name': 'John Smith',
            'email': 'john.smith@example.com',
            'phone': '+1-215-876-8596',
            'companyName': 'Reliance Industries Limited',
            'gender': 'male',
            'address': '268 Bedford Lane Bonita Springs, FL 34135',
        }, {
            'id': 7,
            'name': 'Domnic Harris',
            'email': 'domnic.harris@example.com',
            'phone': '+1-215-785-3841',
            'companyName': 'Oil and Natural Gas Corporation Limited',
            'gender': 'male',
            'address': 'Albany Road Vernon Rockville, CT 06066 822 SE',
        }, {
            'id': 8,
            'name': 'Jimmy Jo',
            'email': 'jimmy.jo@example.com',
            'phone': '+1-215-456-5863',
            'companyName': 'Larsen and Toubro Limited',
            'gender': 'male',
            'address': '16 3rd Road Gallatin, TN 37066',
        },
        {
            'id': 9,
            'name': 'Jon Jimmy',
            'email': 'jon.jo@example.com',
            'phone': '+1-215-456-5863',
            'companyName': 'HCL Technologies Limited',
            'gender': 'male',
            'address': '268 Bedford Lane Bonita Springs, FL 34135',
        },
        {
            'id': 10,
            'name': 'Jhon Jimmy',
            'email': 'jhon.jo@example.com',
            'phone': '+1-215-456-5863',
            'companyName': 'Mahindra and Mahindra Limited',
            'gender': 'male',
            'address': 'Glenwood Court New Rochelle, NY 10801, 7032',
        },
        {
            'id': 11,
            'name': 'Jimmy Smit',
            'email': 'Smit.jo@example.com',
            'phone': '+1-215-456-5863',
            'companyName': 'HDFC Bank Limited',
            'gender': 'male',
            'address': '500 Mill Pond Court Kingsport, TN 37660',
        },
        {
            'id': 12,
            'name': 'Tom',
            'email': 'Tom.jo@example.com',
            'phone': '+1-215-456-5863',
            'companyName': 'ICICI Bank Limited',
            'gender': 'male',
            'address': 'Pelham, AL 35124440 Military Ave.',
        },
        {
            'id': 13,
            'name': 'Tom Jimmy',
            'email': 'JTOM.jo@example.com',
            'phone': '+1-215-456-5863',
            'companyName': 'Wipro Limited',
            'gender': 'male',
            'address': 'Gallatin, TN 37066 16 3rd Road',
        },
    ],
}

export default initValue;